# Generated by Django 4.2.16 on 2025-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
